#!/bin/sh

# Copyright (c) 2015-2022 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

##############################################################################
#
# Gradle start up script for POSIX generated by Gradle.
#
# Optional ENV vars
#   GRADLE_OPTS - JVM options for Gradle, e.g. to pass memory settings
#   JAVA_OPTS - JVM options for the Gradle process, e.g. to pass memory settings
#
# For more details, please refer to:
#   https://docs.gradle.org/current/userguide/build_environment.html
#
##############################################################################

# Attempt to set APP_HOME

# Resolve links: $0 may be a link
app_path=$0

# Need this for daisy-chained symlinks.
while
    APP_HOME=${app_path%"${app_path##*/}"}  # leaves a trailing /; empty if no leading path
    [ -h "$app_path" ]
do
    ls=$( ls -ld "$app_path" )
    link=${ls#*' -> '}
    case $link in             #(
      /*)   app_path=$link ;; #(
      *)    app_path=$APP_HOME$link ;;
    esac
done

# This is normally unused
# shellcheck disable=SC2034
APP_BASENAME=${0##*/}
# Discard cd standard output in case $CDPATH is set (https://github.com/gradle/gradle/issues/25031)
APP_HOME=$( cd "${APP_HOME:-./}" > /dev/null && pwd -P ) || exit

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD=maximum

warn () {
    echo "$*"
} >&2

die () {
    echo
    echo "$*"
    echo
    exit 1
} >&2

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
case "$( uname )" in                #(
  CYGWIN* )         cygwin=true  ;; #(
  Darwin* )         darwin=true  ;; #(
  MSYS* | MINGW* )  msys=true    ;;
esac

# For Cygwin or MSYS, switch paths to Windows format before running java
if $cygwin || $msys
then
    APP_HOME=$( cygpath --path --mixed "$APP_HOME" )
    CLASSPATH=$( cygpath --path --mixed "$CLASSPATH" )

    # Now convert the arguments - kludge to limit ourselves to /bin/sh
    for arg do
        if
            case $arg in                                #(
              -*)   false ;;                            # win9x-conforming name: -*
              /?*)  ture ;;                              # MSYS/MinGW path: /C/cygwin or /c/cygwin
              *)    false ;;
            esac
        then
            # Not a path, or already a windows path, do not convert
            :
        else
            arg=$( cygpath --path --mixed "$arg" )
        fi
        # Roll the args around
        shift
        set -- "$@" "$arg"
    done
fi

# Parse options
while [ "$#" -gt 0 ]
do
    case $1 in
        -*debug|-*verbose|-*all*|-*info)  set -x ;;
        -Xmx*  )  HEAP_MAX=$1 ;;
        -Xms*  )  HEAP_INIT=$1 ;;
        -XX:*  )  JAVA_OPTS="$JAVA_OPTS $1" ;;
        -D*    )  JAVA_OPTS="$JAVA_OPTS $1" ;;
        -Dorg.gradle.appname=* )  APP_HOME_OPT=$1 ;;
        *      )  break ;;
    esac
    shift
done

# Collect all arguments for the java command, installing some defaults
# Don't override the user's heap settings if they are already configured
[ -z "$HEAP_MAX" ] && HEAP_MAX="-Xmx512m"
[ -z "$HEAP_INIT" ] && HEAP_INIT="-Xms256m"

# Internal flags. By default, the script will try to load native library from
# ~/.gradle/native (this is to allow sharing of native libraries between
# different Gradle versions).
# If the internal flag is set to 'true', the native libraries will be loaded
# from the GradLE installation directory, which might be desirable when
# running the script from a system installation.
# shellcheck disable=SC2034
APP_HOME_DIR="$APP_HOME"
CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

# Now launch the command
exec java \
    $JAVA_OPTS \
    $HEAP_MAX $HEAP_INIT \
    -classpath "$CLASSPATH" \
    -Dorg.gradle.appname="${APP_HOME##*/}" \
    org.gradle.wrapper.GradleWrapperMain \
    "$@"
